
EntityCode = {}

local B = 1025
local E = Util.SymbolTable()
local function enum(b, ...)
  for i = 1, select('#', ...) do
    EntityCode[select(i, ...)] = B+b+(i-1)
  end
end

enum( 15, E.BLOCK )
enum( 16, E.SYLVIA )
enum( 16, E.SYLVIA1, E.SYLVIA2, E.SYLVIA3, E.SYLVIA4, E.SYLVIA5, E.SYLVIA6,
          E.SYLVIA7, E.SYLVIA8 )
enum( 24, E.GRAVEN )
enum( 24, E.GRAVEN1, E.GRAVEN2, E.GRAVEN3, E.GRAVEN4, E.GRAVEN5, E.GRAVEN6,
          E.GRAVEN7, E.GRAVEN8 )
enum( 32, E.RUFFIAN, E.TIGER, E.SNAKE, E.BEAR, E.GHOST, E.EYE, E.DRAGON, E.SPIDER )
enum( 40, E.AMMO, E.HEALTH )
enum( 44, E.NOKEY, E.REDKEY, E.YELLOWKEY, E.GREENKEY, E.CYANKEY, E.BLUEKEY,
          E.PURPLEKEY, E.GRAYKEY )
enum( 44, E.NODOOR, E.REDDOOR, E.YELLOWDOOR, E.GREENDOOR, E.CYANDOOR,
          E.BLUEDOOR, E.PURPLEDOOR, E.GRAYDOOR )
enum( 60, E.YELLOWBLOCK, E.MAGENTABLOCK, E.CYANBLOCK )
enum( 63, E.YELLOWEWSLIDER, E.MAGENTAEWSLIDER, E.CYANEWSLIDER )
enum( 66, E.YELLOWNSSLIDER, E.MAGENTANSSLIDER, E.CYANNSSLIDER )
enum( 69, E.SPINNINGGUN )
enum( 70, E.BUNNY )
enum( 70, E.BUNNY1, E.BUNNY2 )
enum( 72, E.ERHARDT )
enum( 72, E.ERHARDT1, E.ERHARDT2, E.ERHARDT3, E.ERHARDT4, E.ERHARDT5,
          E.ERHARDT6, E.ERHARDT7, E.ERHARDT8 )
enum( 80, E.VEX )
enum( 80, E.VEX1, E.VEX2, E.VEX3, E.VEX4 )
enum( 84, E.ABBOT )
enum( 84, E.ABBOT1, E.ABBOT2, E.ABBOT3, E.ABBOT4 )
enum( 88, E.LYNCH )
enum( 88, E.LYNCH1, E.LYNCH2, E.LYNCH3, E.LYNCH4 )
enum( 92, E.SERAPH )
enum( 92, E.SERAPH1, E.SERAPH2, E.SERAPH3, E.SERAPH4 )
enum( 112, E.TRIGGER1, E.TRIGGER2, E.TRIGGER3, E.TRIGGER4, E.TRIGGER5,
           E.TRIGGER6, E.TRIGGER7, E.TRIGGER8 )
enum( 120, E.SPIKE, E.FIRE, E.LAVA, E.ICE, E.WATERN, E.WATERS, E.WATERW, E.WATERE )
enum( 128, E.NOENEMYWALL, E.NOSYLVIAWALL, E.GOOP )
enum( 160, E.SIGN1, E.SIGN2, E.SIGN3, E.SIGN4, E.SIGN5, E.SIGN6, E.SIGN7, E.SIGN8, E.SIGN9,
           E.SIGN10, E.SIGN11, E.SIGN12, E.SIGN13, E.SIGN14, E.SIGN15, E.SIGN16 )
enum( 176, E.TELEPORT1, E.TELEPORT2, E.TELEPORT3, E.TELEPORT4, E.TELEPORT5,
           E.TELEPORT6, E.TELEPORT7, E.TELEPORT8, E.TELEPORT9, E.TELEPORT10,
           E.TELEPORT11, E.TELEPORT12, E.TELEPORT13, E.TELEPORT14, E.TELEPORT15,
           E.TELEPORT16 )

function EntityCode.isSign( ent )
  return (ent >= EntityCode.SIGN1) and (ent <= EntityCode.SIGN16)
end

function EntityCode.isTeleport( ent )
  return (ent >= EntityCode.TELEPORT1) and (ent <= EntityCode.TELEPORT16)
end

